import { Course, SubscriptionTier } from './types';

export const COURSES_DATA: Course[] = [
  {
    id: 'curso-1-scratch-ninja',
    courseNumber: 1,
    title: 'Aventura Scratch Ninja',
    tagline: 'Aprenda a Criar Seus Próprios Jogos do Zero e Domine a Programação!',
    description: 'Curso baseado nas 4 páginas do Guia Completo de Aulas de Tecnologia e Computação 2025, exibido fielmente como slides do PDF.',
    targetAudience: 'Iniciantes & Crianças (6 a 12 Anos)',
    durationHours: 20,
    totalLessons: 4,
    requiredSubscription: SubscriptionTier.STARTER, // Liberado no Plano Básico (STARTER) e Completo (PRO)
    planLabel: 'Incluído no Plano Básico & Completo',
    icon: 'Puzzle',
    colorGradient: 'from-amber-500 via-indigo-600 to-purple-700',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
    pdfGuideAvailable: true,
    thumbnailUrl: '/assets/images/guia_completo_aulas_tecnologia_2025/guia_page-1.png',
    modules: [
      {
        id: 'mod-1-ninja',
        title: 'Módulo 1: O Início da Sua Jornada Ninja',
        description: 'O que são algoritmos, os 3 poderes do Coder (Decomposição, Padrões, Debug) e criação da conta secreta.',
        lessons: [
          {
            id: 'les-1-1',
            title: '1.1 O que é um Algoritmo e Missão Robô',
            duration: '10 min',
            description: 'Entenda como dar instruções 100% exatas para computadores e robôs sem desandar o bolo!',
            isPreview: true,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            pdfMaterialUrl: '/guia_completo_aulas_tecnologia_2025.pdf',
            quizQuestions: [
              {
                question: 'O que é um Algoritmo em programação?',
                options: ['Uma receita de bolo com instruções passo a passo para o computador', 'Um jogo no celular', 'Um robô físico gigante'],
                correctIndex: 0,
              },
            ],
          },
          {
            id: 'les-1-2',
            title: '1.2 Os 3 Poderes do Coder (Decomposição, Padrões, Debug)',
            duration: '15 min',
            description: 'Descubra os truques de mestre para quebrar problemas grandes e encontrar bugs como um detetive virtual.',
            isPreview: true,
          },
          {
            id: 'les-1-3',
            title: '1.3 O que é um Bug e como fazer Debug',
            duration: '12 min',
            description: 'Aprenda por que errar faz parte do aprendizado e como os criadores do Roblox e Minecraft fazem depuração.',
            isPreview: false,
          },
          {
            id: 'les-1-4',
            title: '1.4 Criando sua Conta Secreta no Scratch',
            duration: '10 min',
            description: 'Passo a passo para criar seu perfil oficial no Scratch e salvar seus jogos na nuvem.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-2-ninja',
        title: 'Módulo 2: O Mapa do Tesouro (A Oficina)',
        description: 'As 3 zonas da tela, atores (sprites), biblioteca de cenários e o plano cartesiano X e Y.',
        lessons: [
          {
            id: 'les-2-1',
            title: '2.1 As 3 Zonas da Tela no Scratch',
            duration: '12 min',
            description: 'Conheça a Galeria de Blocos, a Área de Código e o Palco onde a magia acontece ao vivo.',
            isPreview: false,
          },
          {
            id: 'les-2-2',
            title: '2.2 Quem São os Atores (Sprites)?',
            duration: '15 min',
            description: 'Aprenda a escolher e customizar os personagens, vilões e itens do seu jogo.',
            isPreview: false,
          },
          {
            id: 'les-2-3',
            title: '2.3 Escolhendo e Desenhando Cenários',
            duration: '14 min',
            description: 'Use a biblioteca de cenários ou desenhe suas próprias fases e labirintos com o pincel.',
            isPreview: false,
          },
          {
            id: 'les-2-4',
            title: '2.4 O Mapa Secreto de Coordenadas X e Y',
            duration: '18 min',
            description: 'Domine as coordenadas X (horizontal -240 a 240) e Y (vertical -180 a 180).',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-3-ninja',
        title: 'Módulo 3: Movimentação de Super-Herói',
        description: 'Andando, voando, deslizando suavemente e quicando nas bordas da tela.',
        lessons: [
          {
            id: 'les-3-1',
            title: '3.1 O Primeiro Passo: Mova 10 Passos',
            duration: '12 min',
            description: 'Sua primeira pilha de código com a bandeira verde e movimentos para frente e para trás.',
            isPreview: false,
          },
          {
            id: 'les-3-2',
            title: '3.2 A Bússola da Direção (90°, -90°, 0°, 180°)',
            duration: '15 min',
            description: 'Controle a orientação do personagem para jogos de corrida, naves e caminhadas.',
            isPreview: false,
          },
          {
            id: 'les-3-3',
            title: '3.3 Teletransporte e Deslize Suave',
            duration: '16 min',
            description: 'Use "vá para x y" e "deslize por N segs" para criar animações épicas de pulo.',
            isPreview: false,
          },
          {
            id: 'les-3-4',
            title: '3.4 Escudo Quicante de Borda e Rotação',
            duration: '14 min',
            description: 'Evite que seu herói fuja da tela e configure o estilo de rotação esquerda-direita.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-4-ninja',
        title: 'Módulo 4: Aparência e Super Trajes',
        description: 'Animações de caminhada com trajes, balões de fala de HQ, efeitos visuais e camadas.',
        lessons: [
          {
            id: 'les-4-1',
            title: '4.1 Troca de Trajes (Costumes) para Animação',
            duration: '15 min',
            description: 'Alterne rapidamente os desenhos dos trajes para dar a ilusão de caminhada real.',
            isPreview: false,
          },
          {
            id: 'les-4-2',
            title: '4.2 Balões de Fala e Pense estilo HQ',
            duration: '12 min',
            description: 'Adicione diálogos, dicas e balões fofos de conversação no seu jogo.',
            isPreview: false,
          },
          {
            id: 'les-4-3',
            title: '4.3 Efeito Cogumelo do Mario e Fantasma de Cor',
            duration: '18 min',
            description: 'Faça seu personagem crescer, mudar de cor em arco-íris e ficar transparente.',
            isPreview: false,
          },
          {
            id: 'les-4-4',
            title: '4.4 Poder da Invisibilidade e Camadas da Tela',
            duration: '14 min',
            description: 'Use blocos de "escreva/mostre" e "vá para a camada da frente" para itens coletáveis.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-5-ninja',
        title: 'Módulo 5: DJ Scratch (Músicas e Sons)',
        description: 'Efeitos sonoros marcantes, trilha sonora infinita, voz gravada e batidas de bateria.',
        lessons: [
          {
            id: 'les-5-1',
            title: '5.1 Tocando Barulhos Pop, Miau e Efeitos',
            duration: '12 min',
            description: 'Adicione tiros, pulos e explosões sem travar a execução do código.',
            isPreview: false,
          },
          {
            id: 'les-5-2',
            title: '5.2 Trilha Sonora Infinita (Looping de Fundo)',
            duration: '15 min',
            description: 'Junte o bloco "sempre" com blocos de áudio para criar a música de fundo perfeita.',
            isPreview: false,
          },
          {
            id: 'les-5-3',
            title: '5.3 Gravando Vozes do Mal e Risadas com Microfone',
            duration: '15 min',
            description: 'Grave dublagens exclusivas e aplique efeitos de voz de robô ou esquilo.',
            isPreview: false,
          },
          {
            id: 'les-5-4',
            title: '5.4 Ritmo de Bateria Beatbox e Extensão de Música',
            duration: '18 min',
            description: 'Ative instrumentos virtuais de piano, violão e crie ritmos de bateria com código.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-6-ninja',
        title: 'Módulo 6: Teclado, Mouse e Controles',
        description: 'Conectando os controles do jogador ao herói, rádio de mensagens e tempo de espera.',
        lessons: [
          {
            id: 'les-6-1',
            title: '6.1 O que são Eventos e Gatilhos Mágicos',
            duration: '14 min',
            description: 'Entenda os blocos em formato de chapéu que disparam as ações no momento certo.',
            isPreview: false,
          },
          {
            id: 'les-6-2',
            title: '6.2 Controlando o Personagem Pelas Setas do Teclado',
            duration: '16 min',
            description: 'Mova seu herói para Cima, Baixo, Esquerda e Direita ao pressionar as teclas.',
            isPreview: false,
          },
          {
            id: 'les-6-3',
            title: '6.3 Rádio Secreto (Transmita Mensagens entre Atores)',
            duration: '20 min',
            description: 'Comunicação entre atores para disparar "Game Over", portas se abrindo e troféus.',
            isPreview: false,
          },
          {
            id: 'les-6-4',
            title: '6.4 Seguindo a Mão e o Ponteiro do Mouse',
            duration: '15 min',
            description: 'Crie jogos no estilo Fruit Ninja onde o herói segue o toque ou cursor do mouse.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-7-ninja',
        title: 'Módulo 7: Os Loops Mágicos (Repetições)',
        description: 'Repita N vezes, loop infinito sempre, repita até que e loops dentro de loops.',
        lessons: [
          {
            id: 'les-7-1',
            title: '7.1 Por Que Usar Loops? Economize Centenas de Blocos',
            duration: '15 min',
            description: 'Veja a diferença entre código cansativo sem loop vs código Ninja inteligente.',
            isPreview: false,
          },
          {
            id: 'les-7-2',
            title: '7.2 Repita N Vezes e Desenhe Formas Perfeitas',
            duration: '16 min',
            description: 'Crie polígonos e padrões matemáticos incríveis repetindo comandos.',
            isPreview: false,
          },
          {
            id: 'les-7-3',
            title: '7.3 O Loop Infinito "Sempre" e Repita Até Que',
            duration: '18 min',
            description: 'Controle a gravidade, checagem contínua e condições de parada automática.',
            isPreview: false,
          },
          {
            id: 'les-7-4',
            title: '7.4 Loops Aninhados e Animação Fluida de Passos',
            duration: '20 min',
            description: 'Coloque um loop dentro do outro para gerar matrizes de moedas e exércitos de vilões.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-8-ninja',
        title: 'Módulo 8: O Cérebro do Robô (Condições e Sensores)',
        description: 'Tomada de decisão com Se...Então, Radares de toque, Chatbots e Cronômetro da Morte.',
        lessons: [
          {
            id: 'les-8-1',
            title: '8.1 O Bloco Se... Então no Mundo Real',
            duration: '16 min',
            description: 'Ensine seu jogo a tomar decisões: SE pegar a moeda, ENTÃO ganha 10 pontos!',
            isPreview: false,
          },
          {
            id: 'les-8-2',
            title: '8.2 Radares e Sensores de Toque de Cor e Atores',
            duration: '18 min',
            description: 'Detecte batalhas, colisões entre herói e vilão ou pisadas em lava vermelha.',
            isPreview: false,
          },
          {
            id: 'les-8-3',
            title: '8.3 Chatbot Interativo: Perguntas e Respostas',
            duration: '20 min',
            description: 'Crie uma caixa de diálogo que lê a digitação do jogador e responde chamando pelo nome.',
            isPreview: false,
          },
          {
            id: 'les-8-4',
            title: '8.4 O Cronômetro da Morte e Controles Ultra Suaves',
            duration: '22 min',
            description: 'Crie corridas contra o tempo e movimentação arcade sem travamentos.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-9-ninja',
        title: 'Módulo 9: Super Variáveis e Placar de Pontos',
        description: 'Guardando pontos, vidas, moedas, comparadores matemáticos e operadores E, OU, NÃO.',
        lessons: [
          {
            id: 'les-9-1',
            title: '9.1 O que é uma Variável? As Caixas Mágicas',
            duration: '15 min',
            description: 'Armazene Pontos, Vidas, Nível e Recorde em memórias dinâmicas do computador.',
            isPreview: false,
          },
          {
            id: 'les-9-2',
            title: '9.2 Criando o Placar de Pontos e Sistema de Vidas',
            duration: '18 min',
            description: 'Zere o placar no início, adicione pontos ao pegar itens e dê Game Over ao zerar vidas.',
            isPreview: false,
          },
          {
            id: 'les-9-3',
            title: '9.3 Operadores Matemáticos e Comparadores (> < =)',
            duration: '20 min',
            description: 'Some, multiplique e sorteie números aleatórios para caixas surpresa.',
            isPreview: false,
          },
          {
            id: 'les-9-4',
            title: '9.4 Operadores Lógicos (E, OU, NÃO)',
            duration: '22 min',
            description: 'Combine múltiplas regras: SE tiver chave E estiver na porta, ENTÃO libere a fase!',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-10-ninja',
        title: 'Módulo 10: Projeto Final - Pegue a Estrela!',
        description: 'Criação do jogo completo do zero: Herói Ninja, Estrela Mágica, Fantasma e Certificado.',
        lessons: [
          {
            id: 'les-10-1',
            title: '10.1 Game Design: O Plano do Jogo',
            duration: '15 min',
            description: 'Defina as regras do jogo: O Herói, o Objetivo (Estrela) e o Inimigo (Fantasma).',
            isPreview: false,
          },
          {
            id: 'les-10-2',
            title: '10.2 Código do Herói Ninja e Movimentação 4 Direções',
            duration: '25 min',
            description: 'Programe os movimentos ultra suaves nas 4 direções e reset de posição inicial.',
            isPreview: false,
          },
          {
            id: 'les-10-3',
            title: '10.3 Código da Estrela Mágica e Fantasma Perseguidor',
            duration: '30 min',
            description: 'Faça a estrela aparecer em locais aleatórios e o fantasma perseguir o herói.',
            isPreview: false,
          },
          {
            id: 'les-10-4',
            title: '10.4 Publicação no Site e Título de Mestre Coder Ninja!',
            duration: '15 min',
            description: 'Compartilhe seu jogo finalizado e receba o troféu máximo de Criador Profissional!',
            isPreview: false,
          },
        ],
      },
    ],
  },

  {
    id: 'curso-2-python-pro-mode',
    courseNumber: 2,
    title: 'Python Pro Mode',
    tagline: 'A Ponte Definitiva: Como Deixar os Blocos do Scratch e Dominar o Código Real das Big Techs!',
    description: 'Curso baseado nas 41 páginas da Trilha Completa de Tecnologia e Computação 2025, exibindo o conteúdo original do PDF.',
    targetAudience: 'Adolescentes & Devs (13 a 17 Anos)',
    durationHours: 25,
    totalLessons: 41,
    requiredSubscription: SubscriptionTier.PRO, // Exclusivo Plano Completo (PRO)
    planLabel: 'Exclusivo Plano Completo (PRO)',
    icon: 'Cpu',
    colorGradient: 'from-blue-600 via-emerald-600 to-cyan-500',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-400/30',
    pdfGuideAvailable: true,
    thumbnailUrl: '/assets/images/trilha_tecnologia_computacao_2025/trilha_page-1.png',
    modules: [
      {
        id: 'mod2-1-pro',
        title: 'Módulo 1: O Nível Secreto dos Desenvolvedores',
        description: 'A transição dos blocos para o texto profissional em Python, ferramentas VS Code e o mindset Hacker.',
        lessons: [
          {
            id: 'les2-1-1',
            title: '1.1 Você Já Sabe Programar! (Da Lógica ao Código)',
            duration: '15 min',
            description: 'Entenda como a mesma lógica de loops e decisões do Scratch é usada no TikTok, YouTube e OpenAI.',
            isPreview: true,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            pdfMaterialUrl: '/trilha_tecnologia_computacao_2025.pdf',
            quizQuestions: [
              {
                question: 'Por que o Python é considerado a linguagem #1 mundial?',
                options: [
                  'Porque é a linguagem principal usada para criar IA (ChatGPT), Games e possui sintaxe limpa',
                  'Porque só roda em computadores muito velhos',
                  'Porque é feita com blocos coloridos como o Lego'
                ],
                correctIndex: 0,
              },
            ],
          },
          {
            id: 'les2-1-2',
            title: '1.2 Por Que Python É a Linguagem #1 das Big Techs?',
            duration: '18 min',
            description: 'Explore o uso do Python em Inteligência Artificial, desenvolvimento de games com Pygame e sintaxe limpa.',
            isPreview: true,
          },
          {
            id: 'les2-1-3',
            title: '1.3 Do Visual ao Texto: A Anatomia do Código Real',
            duration: '15 min',
            description: 'Compare blocos visuais do Scratch com comandos escritos em arquivos com extensão .py.',
            isPreview: false,
          },
          {
            id: 'les2-1-4',
            title: '1.4 O Mindset Hacker: Depuração, SyntaxError e Traceback',
            duration: '20 min',
            description: 'Aprenda a ler relatórios de erro do Python no terminal como um desenvolvedor profissional.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-2-pro',
        title: 'Módulo 2: O Primeiro Olá Mundo no Terminal',
        description: 'A função print(), strings entre aspas, comentários, calculadora instantânea e múltiplos textos.',
        lessons: [
          {
            id: 'les2-2-1',
            title: '2.1 A Função print() e Saídas no Terminal',
            duration: '15 min',
            description: 'Converta os balões de fala do Scratch na exibição direta de mensagens no console.',
            isPreview: false,
          },
          {
            id: 'les2-2-2',
            title: '2.2 O Segredo das Aspas (Strings)',
            duration: '14 min',
            description: 'Maneira correta de delimitar textos em Python com aspas duplas ou simples e evitar erros de sintaxe.',
            isPreview: false,
          },
          {
            id: 'les2-2-3',
            title: '2.3 Comentários #: Anotações Invisíveis ao Computador',
            duration: '12 min',
            description: 'Organize seu código e documente funções usando o símbolo de hashtag #.',
            isPreview: false,
          },
          {
            id: 'les2-2-4',
            title: '2.4 Python Como Calculadora Instantânea e Concatenação',
            duration: '18 min',
            description: 'Execute operações matemáticas (+ - * /) e junte textos com vírgulas no print().',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-3-pro',
        title: 'Módulo 3: Caixas de Memória (Variáveis & Tipos de Dados)',
        description: 'Criando variáveis, os 4 tipos de dados (int, float, str, bool), f-strings e convenção snake_case.',
        lessons: [
          {
            id: 'les2-3-1',
            title: '3.1 Criando Variáveis em Python (pontos = 100)',
            duration: '15 min',
            description: 'Basta digitar o nome da variável seguido pelo sinal de igual sem menus complicados.',
            isPreview: false,
          },
          {
            id: 'les2-3-2',
            title: '3.2 Os 4 Tipos Principais de Dados (int, float, str, bool)',
            duration: '20 min',
            description: 'Aprenda quando usar números inteiros, decimais, textos e booleanos True ou False.',
            isPreview: false,
          },
          {
            id: 'les2-3-3',
            title: '3.3 Modificando Variáveis com += e -=',
            duration: '16 min',
            description: 'Atalhos de código profissional para somar pontos e subtrair vidas rapidamente.',
            isPreview: false,
          },
          {
            id: 'les2-3-4',
            title: '3.4 F-Strings: Formatação Mágica e Regras de Ouro',
            duration: '22 min',
            description: 'Coloque variáveis dentro de frases elegantes f"Olá {nome}" e siga a convenção snake_case.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-4-pro',
        title: 'Módulo 4: Entrada de Dados (Falando com o Usuário)',
        description: 'A função input(), conversão de tipos (type casting int/float), sanitização .strip().lower() e projetos.',
        lessons: [
          {
            id: 'les2-4-1',
            title: '4.1 A Função input(): Capturando o Teclado',
            duration: '16 min',
            description: 'Abra caixas de digitação no terminal e guarde as respostas dos usuários.',
            isPreview: false,
          },
          {
            id: 'les2-4-2',
            title: '4.2 O Perigo do input() Padrão e Type Casting',
            duration: '20 min',
            description: 'Envolva o input() com int() ou float() para conseguir realizar somas matemáticas.',
            isPreview: false,
          },
          {
            id: 'les2-4-3',
            title: '4.3 Mini-Projeto: Gerador de Cartão Dev / Badge',
            duration: '25 min',
            description: 'Crie uma aplicação completa que lê nome, classe e calcula seu nível de XP.',
            isPreview: false,
          },
          {
            id: 'les2-4-4',
            title: '4.4 Sanitização de Texto com .strip() e .lower()',
            duration: '18 min',
            description: 'Limpe espaços extras e converta entradas para minúsculas evitando falhas no sistema.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-5-pro',
        title: 'Módulo 5: Tomada de Decisão (O Cérebro em Python)',
        description: 'Comando if, a regra sagrada dos 4 espaços de identação, comparadores == !=, if...else, elif e validações.',
        lessons: [
          {
            id: 'les2-5-1',
            title: '5.1 O Comando if (Se)',
            duration: '16 min',
            description: 'Ensine seu script a tomar decisões inteligentes com regras condicionais simples.',
            isPreview: false,
          },
          {
            id: 'les2-5-2',
            title: '5.2 A Regra Sagrada: Identação (Os 4 Espaços)',
            duration: '20 min',
            description: 'Evite o IndentationError entendendo o recuo de código obrigatório do Python.',
            isPreview: false,
          },
          {
            id: 'les2-5-3',
            title: '5.3 Operadores de Comparação (== != >= <=)',
            duration: '18 min',
            description: 'Aprenda a diferença entre 1 sinal de igual (atribuição) e 2 sinais (comparação).',
            isPreview: false,
          },
          {
            id: 'les2-5-4',
            title: '5.4 Estruturas Completa: if...elif...else e Validador de Senha',
            duration: '25 min',
            description: 'Crie menus de múltiplas escolhas e um verificador de acesso de servidores Hacker.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-6-pro',
        title: 'Módulo 6: Operadores Lógicos & Condições Compostas',
        description: 'Operadores and, or, not, sistema de rank de jogos, intervalos elegantes 10 <= x <= 20 e desafios.',
        lessons: [
          {
            id: 'les2-6-1',
            title: '6.1 Os Operadores Lógicos and (E), or (OU), not (NÃO)',
            duration: '18 min',
            description: 'Combine múltiplas checagens para criar regras de acesso complexas.',
            isPreview: false,
          },
          {
            id: 'les2-6-2',
            title: '6.2 Sistema de Rank em Jogos (Radiante, Ouro, Bronze)',
            duration: '22 min',
            description: 'Construa um algoritmo que classifica a pontuação do jogador em ligas competitivas.',
            isPreview: false,
          },
          {
            id: 'les2-6-3',
            title: '6.3 Checando Intervalos Elegantes em Python',
            duration: '15 min',
            description: 'Sintaxe Pythonica incrível para escrever direto 10 <= nivel <= 20 como na matemática.',
            isPreview: false,
          },
          {
            id: 'les2-6-4',
            title: '6.4 Desafio Pro: O Guardião da Dungeon',
            duration: '25 min',
            description: 'Crie a lógica de acesso ao chefe final baseada em HP, itens no inventário e classe.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-7-pro',
        title: 'Módulo 7: Loops de Alto Desempenho (Repetições)',
        description: 'Laços for com range(), laço infinito while True, break, continue e simulador de contagem regressiva.',
        lessons: [
          {
            id: 'les2-7-1',
            title: '7.1 O Loop for e a Função range(início, fim, passo)',
            duration: '18 min',
            description: 'Automatize tarefas repetitivas contando números e executando tiros ou sequências.',
            isPreview: false,
          },
          {
            id: 'les2-7-2',
            title: '7.2 O Loop Infinito: while True (Game Loop)',
            duration: '20 min',
            description: 'Crie o loop principal de sustentação que mantém programas e jogos rodando continuamente.',
            isPreview: false,
          },
          {
            id: 'les2-7-3',
            title: '7.3 Quebrando Loops com break e Pulando com continue',
            duration: '18 min',
            description: 'Force a saída imediata ao morrer ou pule rodadas específicas da repetição.',
            isPreview: false,
          },
          {
            id: 'les2-7-4',
            title: '7.4 Simulador de Lançamento de Foguete com import time',
            duration: '22 min',
            description: 'Use o módulo de tempo nativo do Python para criar contagens regressivas reais com tempo de pausa.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-8-pro',
        title: 'Módulo 8: Coleções Espaciais (Listas e Arrays)',
        description: 'Criando listas, índice zero, métodos .append(), .pop(), len(), iteração com for e sorteio de loot.',
        lessons: [
          {
            id: 'les2-8-1',
            title: '8.1 Criando Listas em Python e o Índice Zero',
            duration: '18 min',
            description: 'Guarde centenas de itens na memória e aprenda por que em código o primeiro item é o Índice 0.',
            isPreview: false,
          },
          {
            id: 'les2-8-2',
            title: '8.2 Adicionando e Removendo Itens: .append(), .pop() e len()',
            duration: '20 min',
            description: 'Gerencie a mochila e inventário do jogador coletando loots e usando poções.',
            isPreview: false,
          },
          {
            id: 'les2-8-3',
            title: '8.3 Percorrendo Listas com Loop for',
            duration: '16 min',
            description: 'Exiba relatórios de membros da guilda conectados e listas dinâmicas no console.',
            isPreview: false,
          },
          {
            id: 'les2-8-4',
            title: '8.4 Sorteio de Loot Aleatório com o Módulo random',
            duration: '22 min',
            description: 'Use random.choice() para sortear prêmios surpresa, armas lendárias e baús misteriosos.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-9-pro',
        title: 'Módulo 9: Funções (Criando Nossos Próprios Comandos)',
        description: 'Definindo funções com def, parâmetros, retorno return, princípio DRY e gerador de batalhas.',
        lessons: [
          {
            id: 'les2-9-1',
            title: '9.1 O que é uma Função em Python? (def)',
            duration: '18 min',
            description: 'Crie seus próprios comandos customizados e organize seu código de forma limpa.',
            isPreview: false,
          },
          {
            id: 'les2-9-2',
            title: '9.2 Parâmetros: As Entradas Dinâmicas da Função',
            duration: '20 min',
            description: 'Passe variáveis como argumentos para personalizar o resultado de cada execução.',
            isPreview: false,
          },
          {
            id: 'les2-9-3',
            title: '9.3 O Retorno de Dados com return',
            duration: '22 min',
            description: 'Faça sua função calcular fórmulas matemáticas ou danos de ataque e devolver a resposta.',
            isPreview: false,
          },
          {
            id: 'les2-9-4',
            title: '9.4 O Princípio DRY (Don\'t Repeat Yourself) & Gerador D20',
            duration: '25 min',
            description: 'Aprenda as boas práticas das Big Techs e crie um rolador de dados de RPG em função.',
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod2-10-pro',
        title: 'Módulo 10: Projeto Final - RPG Cyberpunk & REVISÃO GERAL',
        description: 'Construção do jogo completo RPG Cyberpunk Neo-City, Game Loop, Combate, Loot e Certificação DEVELOPER PRO.',
        lessons: [
          {
            id: 'les2-10-1',
            title: '10.1 Arquitetura do Jogo & Mapa de Revisão Geral',
            duration: '20 min',
            description: 'Planeje os 4 pilares do RPG: Status, Game Loop, Sistema de Batalha e Funções.',
            isPreview: false,
          },
          {
            id: 'les2-10-2',
            title: '10.2 Etapa 1: Início, Nick e Variáveis do Player',
            duration: '25 min',
            description: 'Reafirmando o aprendizado com a criação de inventário inicial e formatação F-String.',
            isPreview: false,
          },
          {
            id: 'les2-10-3',
            title: '10.3 Etapa 2 & 3: Game Loop Principal & Sistema de Batalha',
            duration: '35 min',
            description: 'Programe o loop while hp > 0, sorteio de dano aleatório e ganho de moedas Cyberpunk.',
            isPreview: false,
          },
          {
            id: 'les2-10-4',
            title: '10.4 Etapa 4: Funções Surpresa & Certificado DEVELOPER PRO!',
            duration: '20 min',
            description: 'Conclua a simulação de Neo-City e conquiste seu selo máximo de Desenvolvedor Python!',
            isPreview: false,
          },
        ],
      },
    ],
  },
];
